# -*- coding: utf-8 -*-
"""date.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mvMi-G50qU3-RSCWiCBFEweQP0Gi1-KT
"""

!pip install num2words

!pip install word2number

"""test cases = {twenty-second october 1998}, {22 10 1998}, {1998 10 22}

output = ["22/10/1998"]
"""

def dob_words:  
  from num2words import num2words
  from word2number import w2n
  import inflect
  import numpy as np
  p = inflect.engine()
  Dates = []

  for i in range(1,32):
      Dates.append(num2words(i, to = 'ordinal'))
  Dates = np.array(Dates)
  print(Dates)

  print('Enter DOB: ')
  date = input()
  DOB = []
  date = date.split(" ")    #['first', 'december', '1990']
  date = np.array(date)
  for i in range(len(Dates)):
    if date[0] == Dates[i]:
      DOB.append(i+1)
  DOB.append("/")

  Months = {"january":1, "february":2, "march":3, "april":4, "may":5, "june":6, "july":7, "august":8, "september":9, "october":10, "november":11, "december":12}
  for i in Months:
    if date[1].lower()==i:
      DOB.append(Months[i])
  DOB.append("/")

  year = " " 
  year = year.join(date[2:])

  date[2] = w2n.word_to_num(year)
  DOB.append(date[2])

  DOB = np.array(DOB)
  birthday = " "
  birthday = birthday.join(DOB[0:])
  bday = []
  bday.append(birthday)
  print(bday)

def dob_number: 
  print('Enter DOB: ')
  date = input()            #[22 10 1998]
  DOB = []
date = date.split(" ")    #[22 10 1998]

date[2] = " ".join(date[2:])
date = date[0:3]
if date[0].isalpha():
  for d in date:
    print(d)
    d = w2n.word_to_num(d)
    DOB.append(d)
print("date", date)
date = np.array(DOB)
print(date)
birthday = ""
for i in range (len(date)):
      if date[0] <= 31:
        birthday += str(date[i]) 
        birthday += "/"
      else:
        birthday += date[len(date)-i-1]
        birthday += "/"
birthday = birthday[:-1]
bday = []
bday.append(birthday)
print(bday)

